[package]
name = "redscript-mkdocs"
version = "1.0.0"
authors = ["Reece Sheppard reece@flib.com.au"]
edition = "2018"

[dependencies]
redscript = { git = "https://github.com/jac3km4/redscript", branch = "master" }
gumdrop = "0.8"
log = "0.4"
simplelog = "0.10"
