[package]
name = "parser"
version = "1.0.0"
authors = ["Reece Sheppard reece@flib.com.au"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
peg = "0.7"

[features]
trace = ["peg/trace"]
