site_name: redscript-mkdocs
site_dir: ../site
theme:
  name: material
  language: en
plugins:
  - search:
      prebuild_index: true
  - minify:
      minify_html: true
      htmlmin_opts:
          remove_comments: true
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
